### ISSUE TITLE
Missing source files after composer install

### ISSUE THREAD

**Issue by kiettran** [nijens/openapi-bundle#43]
After installing the openapi bundle, the source files could not be found. The `src` directory is empty. This happens on different composer versions (1.9.x, 1.10.x and 2.x) and on different projects. From existing to new symfony 5 projects.

**Comment by niels-nijens** [comment]
Thanks for reporting! This has been fixed in version [1.0.1](https://github.com/nijens/openapi-bundle/releases/tag/1.0.1).
