### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hansgoed** [nijens/openapi-bundle#6]
In openapi-bundle/src/EventListener/JsonRequestBodyValidationSubscriber.php: 
* Some exceptions are thrown, however the PHPDoc does not contain `@throws` tags
* openapi_resource and openapi_json_request_validation_pointer are re-used, maybe create constants for them?

In openapi-bundle/src/Json/JsonPointer.php:
* Class documentation is a little weak

**Comment by niels-nijens** [comment]
Thanks for the feedback. All good points. I will make the necessary changes. :+1:
